version: '3.1'

services:
  auth:
    image: alexsantossilva/ms-auth-spring
    container_name: ms_auth
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auth
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ubuntu
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_PRODUCER_BOOTSTRAP-SERVERS: kafka:29092
      TOPIC_NAME_PRODUCER: ms.teams
    depends_on:
      - postgres
      - kafka
    ports:
      - '8080:8080'

  consumer:
    image: alexsantossilva/ms-consumer-spring
    container_name: ms_consumer
    env_file:
      - configs/consumer/consumer.env
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:29092
      TOPIC_NAME_CONSUMER: ms.teams
    depends_on:
      - kafka

  postgres:
    image: alexsantossilva/88aoj-postgres
    container_name: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "ubuntu"
      POSTGRES_DB: "auth"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - postgres

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092